// import { Address } from '../../types/types';
// export const addresses: Address[] = [
//   {
//     id: 1,
//     name: 'John Smith',
//     address: '4455 Landing Lange, APT 4',
//     city: 'Louisville',
//     state: 'KY',
//     zip: '40018-1234',
//     isDefault: true,
//     phone: '+1 502-123-4567',
//   },
//   {
//     id: 2,
//     name: 'Jane Doe',
//     address: '123 Maple Street, Suite 12',
//     city: 'San Francisco',
//     state: 'CA',
//     zip: '94111',
//     isDefault: false,
//     phone: '+1 415-987-6543',
//   },
//   {
//     id: 3,
//     name: 'Michael Johnson',
//     address: '789 Cedar Ave, Floor 2',
//     city: 'Austin',
//     state: 'TX',
//     zip: '73301',
//     isDefault: false,
//     phone: '+1 512-321-6549',
//   },
//   {
//     id: 4,
//     name: 'Emily Davis',
//     address: '555 Oak Drive, Unit 3B',
//     city: 'Chicago',
//     state: 'IL',
//     zip: '60616',
//     isDefault: false,
//     phone: '+1 312-456-7890',
//   },
//   {
//     id: 5,
//     name: 'Robert Wilson',
//     address: '101 Pine Road, APT 7',
//     city: 'Denver',
//     state: 'CO',
//     zip: '80203',
//     isDefault: false,
//     phone: '+1 720-543-2100',
//   },
// ];
