import ShopProfile from '../../assets/shop-images/shop-profile.png';

export const posts = [
  {
    id: 1,
    title: 'Official new launch thread re: the new beads styles',
    author: 'Creative Beadz Store',
    authorType: 'buyer',
    isNew: true,
    replies: '5',
    views: '50.5k',
    avatarUrl: ShopProfile,
    content: `Hey everyone,
We're so excited to announce the launch of our latest collection of beads! We've been hard at work creating unique and stunning designs that will elevate your jewelry.
From bold and colorful statement pieces to delicate and minimalist options, there's something for everyone. Our new collection features a variety of materials, including glass, acrylic, and semi-precious stones.
What are your thoughts on the new styles? Have you tried any of them yet? Share your favorite designs and let's discuss!`,
    repliesList: [
      { content: "I'm absolutely in love with the new turquoise beads!" },
      { content: 'The acrylic beads are so bold!' },
    ],
  },
  {
    id: 2,
    title: 'Marketing Tips',
    author: 'Creative Beadz Store',
    authorType: 'seller',
    isNew: true,
    replies: '1.3k',
    views: '50.5k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Here are some marketing tips to boost your sales...`,
    repliesList: [
      { content: 'Thanks for the tips, they were really helpful!' },
      { content: 'Great advice!' },
    ],
  },
  {
    id: 3,
    title: 'Event Update',
    author: 'Creative Beadz Store',
    authorType: 'buyer',
    isNew: false,
    replies: '300',
    views: '10k',
    avatarUrl: ShopProfile,
    content: `Don't miss the upcoming event on bead crafting...`,
    repliesList: [
      { content: 'Looking forward to the event!' },
      { content: 'Excited to join!' },
    ],
  },
  {
    id: 4,
    title: 'Seller’s Tips',
    author: 'Creative Beadz Store',
    authorType: 'seller',
    isNew: false,
    replies: '1.1k',
    views: '40.3k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Here are some tips to optimize your product listings...`,
    repliesList: [
      { content: 'Very informative, thanks!' },
      { content: 'I applied the tips and saw results.' },
    ],
  },
  {
    id: 5,
    title: 'Best Sellers in 2024',
    author: 'Crafted Essentials',
    authorType: 'seller',
    isNew: true,
    replies: '950',
    views: '30.5k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Check out the best-selling products of the year...`,
    repliesList: [
      { content: 'Great list!' },
      { content: 'Thanks for sharing!' },
    ],
  },
  {
    id: 6,
    title: 'Customer Service Tips',
    author: 'Customer Connect',
    authorType: 'buyer',
    isNew: true,
    replies: '870',
    views: '25.4k',
    avatarUrl: ShopProfile,
    content: `Tips on how to improve customer service...`,
    repliesList: [
      { content: 'Good to know!' },
      { content: 'Will apply these tips to my shop.' },
    ],
  },
  {
    id: 7,
    title: 'Marketing with Social Media',
    author: 'Creative Beadz Store',
    authorType: 'seller',
    isNew: false,
    replies: '600',
    views: '15.2k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Boost your sales using social media marketing...`,
    repliesList: [
      { content: 'Amazing strategy!' },
      { content: 'I will definitely try this.' },
    ],
  },
  {
    id: 8,
    title: 'Crafting Beads with Style',
    author: 'Bead Craft Masters',
    authorType: 'buyer',
    isNew: true,
    replies: '250',
    views: '5.9k',
    avatarUrl: ShopProfile,
    content: `Learn the latest bead crafting techniques...`,
    repliesList: [
      { content: 'Very insightful!' },
      { content: 'I learned a lot.' },
    ],
  },
  {
    id: 9,
    title: 'Top Shops of the Month',
    author: 'Marketplace Reviews',
    authorType: 'seller',
    isNew: false,
    replies: '400',
    views: '20k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Here are the top shops of this month...`,
    repliesList: [
      { content: 'Congratulations to all the shops!' },
      { content: 'Aspiring to be on this list soon.' },
    ],
  },
  {
    id: 10,
    title: 'Packaging Best Practices',
    author: 'Shipping Experts',
    authorType: 'seller',
    isNew: false,
    replies: '300',
    views: '18.1k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Ensure your products arrive safely with these packaging tips...`,
    repliesList: [
      { content: 'Great tips, very useful!' },
      { content: 'I’ll follow this for my shipments.' },
    ],
  },
  {
    id: 11,
    title: 'Product Photography Tips',
    author: 'Photo Pro',
    authorType: 'seller',
    isNew: false,
    replies: '450',
    views: '28.3k',
    avatarUrl: 'https://via.placeholder.com/50',
    content: `Improve your product images with these simple photography tips...`,
    repliesList: [
      { content: 'Amazing results after applying these tips!' },
      { content: 'I’m loving the improvement in my product photos.' },
    ],
  },
  {
    id: 12,
    title: 'Customer Loyalty Programs',
    author: 'Loyalty Boost',
    authorType: 'buyer',
    isNew: true,
    replies: '700',
    views: '22.9k',
    avatarUrl: ShopProfile,
    content: `Create effective loyalty programs for your customers...`,
    repliesList: [
      { content: 'Great insights!' },
      { content: 'We’ve already implemented this in our shop.' },
    ],
  },
];
