import ProductImage from '../../assets/product-image/product1.png';
import Image2 from '../../assets/category-images/clothingcategory.png';
import Image3 from '../../assets/category-images/foodcategory.png';
import Image5 from '../../assets/category-images/foodstuff-category.png';
import Image4 from '../../assets/category-images/jewelriescategories.png';

// Sample Orders Data
export const ordersData = [
  {
    orderId: 'Bk21334567',
    product: 'Pattern African Exquisite Collage Art on Stretched Canvas',
    productImage: ProductImage,
    date: '4th May, 2024',
    quantity: '3x',
    total: '$230',
    storeName: 'Creative Artz Store',
    status: 'Completed',
    expectedDelivery: '11th May, 2024',
  },
  {
    orderId: 'Bk21334568',
    product: 'Modern Abstract Wall Art',
    productImage: ProductImage,
    date: '10th May, 2024',
    quantity: '2x',
    total: '$150',
    storeName: 'Urban Art House',
    status: 'Pending',
    expectedDelivery: '17th May, 2024',
  },
  {
    orderId: 'Bk21334569',
    product: 'Abstract African Canvas Painting',
    productImage: ProductImage,
    date: '12th May, 2024',
    quantity: '1x',
    total: '$210.95',
    storeName: 'Africa Art Store',
    status: 'Cancelled',
    expectedDelivery: '19th May, 2024',
  },
  {
    orderId: 'Bk21334570',
    product: 'Traditional African Wooden Sculpture',
    productImage: Image2,
    date: '15th May, 2024',
    quantity: '2x',
    total: '$120.95',
    storeName: 'Africa Art Store',
    status: 'Pending',
    expectedDelivery: '22nd May, 2024',
  },
  {
    orderId: 'Bk21334571',
    product: 'African Mask Wall Decor',
    productImage: Image3,
    date: '18th May, 2024',
    quantity: '5x',
    total: '$404.75',
    storeName: 'Africa Art Store',
    status: 'Completed',
    expectedDelivery: '25th May, 2024',
  },
  {
    orderId: 'Bk21334572',
    product: 'Handwoven African Baskets',
    productImage: Image4,
    date: '20th May, 2024',
    quantity: '3x',
    total: '$122.85',
    storeName: 'Africa Art Store',
    status: 'Cancelled',
    expectedDelivery: '27th May, 2024',
  },
  {
    orderId: 'Bk21334573',
    product: 'African Tribal Painting Set',
    productImage: Image5,
    date: '22nd May, 2024',
    quantity: '1x',
    total: '$299.95',
    storeName: 'Africa Art Store',
    status: 'Completed',
    expectedDelivery: '29th May, 2024',
  },
  {
    orderId: 'Bk21334574',
    product: 'Ceramic African Vases',
    productImage: ProductImage,
    date: '25th May, 2024',
    quantity: '4x',
    total: '$283.80',
    storeName: 'Africa Art Store',
    status: 'Completed',
    expectedDelivery: '1st June, 2024',
  },
  {
    orderId: 'Bk21334575',
    product: 'African Inspired Metal Wall Art',
    productImage: Image2,
    date: '27th May, 2024',
    quantity: '2x',
    total: '$441.90',
    storeName: 'Africa Art Store',
    status: 'Pending',
    expectedDelivery: '3rd June, 2024',
  },
  {
    orderId: 'Bk21334576',
    product: 'African Elephant Statue',
    productImage: Image3,
    date: '30th May, 2024',
    quantity: '1x',
    total: '$85.95',
    storeName: 'Africa Art Store',
    status: 'Cancelled',
    expectedDelivery: '6th June, 2024',
  },
  {
    orderId: 'Bk21334577',
    product: 'African Tapestry Wall Hanging',
    productImage: Image4,
    date: '1st June, 2024',
    quantity: '2x',
    total: '$241.90',
    storeName: 'Africa Art Store',
    status: 'Pending',
    expectedDelivery: '8th June, 2024',
  },
  {
    orderId: 'Bk21334578',
    product: 'African Bead Art Portraits',
    productImage: Image5,
    date: '3rd June, 2024',
    quantity: '1x',
    total: '$180.95',
    storeName: 'Africa Art Store',
    status: 'Completed',
    expectedDelivery: '10th June, 2024',
  },
  {
    orderId: 'Bk21334579',
    product: 'Kente Print Fabric',
    productImage: ProductImage,
    date: '5th June, 2024',
    quantity: '6x',
    total: '$215.70',
    storeName: 'African Fabrics Store',
    status: 'Completed',
    expectedDelivery: '12th June, 2024',
  },
  {
    orderId: 'Bk21334580',
    product: 'Ankara Print Headwrap',
    productImage: Image2,
    date: '8th June, 2024',
    quantity: '10x',
    total: '$159.50',
    storeName: 'African Fabrics Store',
    status: 'Pending',
    expectedDelivery: '15th June, 2024',
  },
  {
    orderId: 'Bk21334581',
    product: 'African Print Tote Bag',
    productImage: Image3,
    date: '10th June, 2024',
    quantity: '2x',
    total: '$51.90',
    storeName: 'African Fabrics Store',
    status: 'Cancelled',
    expectedDelivery: '17th June, 2024',
  },
  {
    orderId: 'Bk21334582',
    product: 'Dashiki African Shirt',
    productImage: Image4,
    date: '12th June, 2024',
    quantity: '1x',
    total: '$35.95',
    storeName: 'African Fabrics Store',
    status: 'Pending',
    expectedDelivery: '19th June, 2024',
  },
  {
    orderId: 'Bk21334583',
    product: 'Wax Print Fabric',
    productImage: Image5,
    date: '15th June, 2024',
    quantity: '3x',
    total: '$122.85',
    storeName: 'African Fabrics Store',
    status: 'Completed',
    expectedDelivery: '22nd June, 2024',
  },
  {
    orderId: 'Bk21334584',
    product: 'African Print Wrap Skirt',
    productImage: ProductImage,
    date: '17th June, 2024',
    quantity: '2x',
    total: '$81.90',
    storeName: 'African Fabrics Store',
    status: 'Completed',
    expectedDelivery: '24th June, 2024',
  },
  {
    orderId: 'Bk21334585',
    product: 'Batik Print Scarf',
    productImage: Image2,
    date: '19th June, 2024',
    quantity: '4x',
    total: '$83.80',
    storeName: 'African Fabrics Store',
    status: 'Cancelled',
    expectedDelivery: '26th June, 2024',
  },
  {
    orderId: 'Bk21334586',
    product: 'Mud Cloth Throw Blanket',
    productImage: Image3,
    date: '21st June, 2024',
    quantity: '2x',
    total: '$171.90',
    storeName: 'African Fabrics Store',
    status: 'Completed',
    expectedDelivery: '28th June, 2024',
  },
  {
    orderId: 'Bk21334587',
    product: 'African Maxi Dress',
    productImage: Image4,
    date: '24th June, 2024',
    quantity: '1x',
    total: '$60.95',
    storeName: 'African Fabrics Store',
    status: 'Completed',
    expectedDelivery: '1st July, 2024',
  },
  {
    orderId: 'Bk21334588',
    product: 'Kente Stole',
    productImage: Image5,
    date: '26th June, 2024',
    quantity: '5x',
    total: '$154.75',
    storeName: 'African Fabrics Store',
    status: 'Pending',
    expectedDelivery: '3rd July, 2024',
  },
];
