import ProductImage from '../../assets/product-image/product1.png';
import Image2 from '../../assets/category-images/clothingcategory.png';
import Image3 from '../../assets/category-images/foodcategory.png';
import Image5 from '../../assets/category-images/foodstuff-category.png';
import Image4 from '../../assets/category-images/jewelriescategories.png';

export const orderData = [
  {
    orderId: 'Bk21334567',
    productName: 'Pattern African Exquisite Collage Art on Stretched Canvas',
    productImage: ProductImage,
    price: '$230',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '4th May, 2024',
  },
  {
    orderId: 'Bk21334568',
    productName: 'Modern Abstract Wall Art',
    productImage: ProductImage,
    price: '$150',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '10th May, 2024',
  },
  {
    orderId: 'Bk21334569',
    productName: 'Abstract African Canvas Painting',
    productImage: ProductImage,
    price: '$210.95',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '12th May, 2024',
  },
  {
    orderId: 'Bk21334570',
    productName: 'Traditional African Wooden Sculpture',
    productImage: Image2,
    price: '$120.95',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '15th May, 2024',
  },
  {
    orderId: 'Bk21334571',
    productName: 'African Mask Wall Decor',
    productImage: Image3,
    price: '$404.75',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '18th May, 2024',
  },
  {
    orderId: 'Bk21334572',
    productName: 'Handwoven African Baskets',
    productImage: Image4,
    price: '$122.85',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '20th May, 2024',
  },
  {
    orderId: 'Bk21334573',
    productName: 'African Tribal Painting Set',
    productImage: Image5,
    price: '$299.95',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '22nd May, 2024',
  },
  {
    orderId: 'Bk21334574',
    productName: 'Ceramic African Vases',
    productImage: ProductImage,
    price: '$283.80',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '25th May, 2024',
  },
  {
    orderId: 'Bk21334575',
    productName: 'African Inspired Metal Wall Art',
    productImage: Image2,
    price: '$441.90',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '27th May, 2024',
  },
  {
    orderId: 'Bk21334576',
    productName: 'African Elephant Statue',
    productImage: Image3,
    price: '$85.95',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '30th May, 2024',
  },
  {
    orderId: 'Bk21334577',
    productName: 'African Tapestry Wall Hanging',
    productImage: Image4,
    price: '$241.90',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '1st June, 2024',
  },
  {
    orderId: 'Bk21334578',
    productName: 'African Bead Art Portraits',
    productImage: Image5,
    price: '$180.95',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '3rd June, 2024',
  },
  {
    orderId: 'Bk21334579',
    productName: 'Kente Print Fabric',
    productImage: ProductImage,
    price: '$215.70',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '5th June, 2024',
  },
  {
    orderId: 'Bk21334580',
    productName: 'Ankara Print Headwrap',
    productImage: Image2,
    price: '$159.50',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '8th June, 2024',
  },
  {
    orderId: 'Bk21334581',
    productName: 'African Print Tote Bag',
    productImage: Image3,
    price: '$51.90',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '10th June, 2024',
  },
  {
    orderId: 'Bk21334582',
    productName: 'Dashiki African Shirt',
    productImage: Image4,
    price: '$35.95',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '12th June, 2024',
  },
  {
    orderId: 'Bk21334583',
    productName: 'Wax Print Fabric',
    productImage: Image5,
    price: '$122.85',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '15th June, 2024',
  },
  {
    orderId: 'Bk21334584',
    productName: 'African Print Wrap Skirt',
    productImage: ProductImage,
    price: '$81.90',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '17th June, 2024',
  },
  {
    orderId: 'Bk21334585',
    productName: 'Batik Print Scarf',
    productImage: Image2,
    price: '$83.80',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '19th June, 2024',
  },
  {
    orderId: 'Bk21334586',
    productName: 'Mud Cloth Throw Blanket',
    productImage: Image3,
    price: '$171.90',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '21st June, 2024',
  },
  {
    orderId: 'Bk21334587',
    productName: 'African Maxi Dress',
    productImage: Image4,
    price: '$60.95',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '24th June, 2024',
  },
  {
    orderId: 'Bk21334588',
    productName: 'Kente Stole',
    productImage: Image5,
    price: '$154.75',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '26th June, 2024',
  },
  {
    orderId: 'Bk21334589',
    productName: 'African Print Jacket',
    productImage: ProductImage,
    price: '$128.50',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '29th June, 2024',
  },
  {
    orderId: 'Bk21334590',
    productName: 'African Tribal Necklace',
    productImage: Image2,
    price: '$75.20',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '1st July, 2024',
  },
  {
    orderId: 'Bk21334591',
    productName: 'African Wooden Mask',
    productImage: Image3,
    price: '$55.00',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '3rd July, 2024',
  },
  {
    orderId: 'Bk21334592',
    productName: 'Hand-carved African Sculpture',
    productImage: Image4,
    price: '$180.00',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '5th July, 2024',
  },
  {
    orderId: 'Bk21334593',
    productName: 'African Patterned Curtains',
    productImage: Image5,
    price: '$250.00',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '7th July, 2024',
  },
  {
    orderId: 'Bk21334594',
    productName: 'African Beaded Anklet',
    productImage: ProductImage,
    price: '$45.00',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '9th July, 2024',
  },
  {
    orderId: 'Bk21334595',
    productName: 'Handmade African Jewelry Set',
    productImage: Image2,
    price: '$160.00',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '11th July, 2024',
  },
  {
    orderId: 'Bk21334596',
    productName: 'African Handwoven Basket',
    productImage: Image3,
    price: '$90.50',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '13th July, 2024',
  },
  {
    orderId: 'Bk21334597',
    productName: 'Kuba Cloth Pillow Cover',
    productImage: Image4,
    price: '$35.75',
    status: 'Pending',
    payment: 'Unpaid',
    shipping: 'Pending',
    date: '15th July, 2024',
  },
  {
    orderId: 'Bk21334598',
    productName: 'African Leather Sandals',
    productImage: Image5,
    price: '$120.00',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '17th July, 2024',
  },
  {
    orderId: 'Bk21334599',
    productName: 'Mudcloth Table Runner',
    productImage: ProductImage,
    price: '$60.00',
    status: 'Completed',
    payment: 'Paid',
    shipping: 'Shipped',
    date: '19th July, 2024',
  },
  {
    orderId: 'Bk21334600',
    productName: 'African Patchwork Quilt',
    productImage: Image2,
    price: '$300.00',
    status: 'Cancelled',
    payment: 'Refunded',
    shipping: 'Cancelled',
    date: '21st July, 2024',
  },
];
