import ProductImage1 from '../../assets/category-images/clothingcategory.png';
import ProductImage2 from '../../assets/category-images/fabriccategory.png';
import ProductImage3 from '../../assets/category-images/fashioncategory.png';
import ProductImage4 from '../../assets/category-images/foodcategory.png';
import ProductImage5 from '../../assets/category-images/somethingcategory.png';

export const storeProductsData = [
  {
    productId: 'P12345678',
    productImage: ProductImage1,
    productName: 'Pattern African Exquisite Collage Art on Stretched Canvas',
    variation: 'Size: Large',
    price: 230,
    inStock: 15,
    status: 'Active',
  },
  {
    productId: 'P12345679',
    productImage: ProductImage2,
    productName: 'Modern Abstract Wall Art',
    variation: 'Size: Medium',
    price: 150,
    inStock: 8,
    status: 'Active',
  },
  {
    productId: 'P12345680',
    productImage: ProductImage3,
    productName: 'Abstract African Canvas Painting',
    variation: 'Size: Small',
    price: 110,
    inStock: 12,
    status: 'Inactive',
  },
  {
    productId: 'P12345681',
    productImage: ProductImage4,
    productName: 'Traditional African Wooden Sculpture',
    variation: 'Color: Dark Wood',
    price: 200,
    inStock: 7,
    status: 'Active',
  },
  {
    productId: 'P12345682',
    productImage: ProductImage5,
    productName: 'African Mask Wall Decor',
    variation: 'Material: Metal',
    price: 320,
    inStock: 5,
    status: 'Active',
  },
  {
    productId: 'P12345683',
    productImage: ProductImage1,
    productName: 'Handwoven African Baskets',
    variation: 'Size: Large',
    price: 180,
    inStock: 10,
    status: 'Inactive',
  },
  {
    productId: 'P12345684',
    productImage: ProductImage2,
    productName: 'African Tribal Painting Set',
    variation: 'Type: Canvas',
    price: 290,
    inStock: 18,
    status: 'Active',
  },
  {
    productId: 'P12345685',
    productImage: ProductImage3,
    productName: 'Ceramic African Vases',
    variation: 'Size: Small',
    price: 85,
    inStock: 20,
    status: 'Active',
  },
  {
    productId: 'P12345686',
    productImage: ProductImage4,
    productName: 'African Inspired Metal Wall Art',
    variation: 'Size: Large',
    price: 440,
    inStock: 12,
    status: 'Inactive',
  },
  {
    productId: 'P12345687',
    productImage: ProductImage5,
    productName: 'Kente Print Fabric',
    variation: 'Size: Small',
    price: 50,
    inStock: 25,
    status: 'Active',
  },
  {
    productId: 'P12345688',
    productImage: ProductImage1,
    productName: 'Hand-carved Wooden Mask',
    variation: 'Color: Black',
    price: 300,
    inStock: 6,
    status: 'Active',
  },
  {
    productId: 'P12345689',
    productImage: ProductImage2,
    productName: 'African Animal Sculpture Set',
    variation: 'Type: Bronze',
    price: 180,
    inStock: 22,
    status: 'Inactive',
  },
  {
    productId: 'P12345690',
    productImage: ProductImage3,
    productName: 'African Tribal Masks Set',
    variation: 'Size: Medium',
    price: 215,
    inStock: 11,
    status: 'Active',
  },
  {
    productId: 'P12345691',
    productImage: ProductImage4,
    productName: 'Batik Printed Fabric',
    variation: 'Color: Blue',
    price: 120,
    inStock: 18,
    status: 'Active',
  },
  {
    productId: 'P12345692',
    productImage: ProductImage5,
    productName: 'Handwoven African Textile',
    variation: 'Size: Medium',
    price: 75,
    inStock: 28,
    status: 'Active',
  },
  {
    productId: 'P12345693',
    productImage: ProductImage1,
    productName: 'African Bead Necklace',
    variation: 'Color: Red',
    price: 90,
    inStock: 35,
    status: 'Inactive',
  },
  {
    productId: 'P12345694',
    productImage: ProductImage2,
    productName: 'Wooden Handcrafted Jewelry Box',
    variation: 'Material: Mahogany',
    price: 85,
    inStock: 16,
    status: 'Active',
  },
  {
    productId: 'P12345695',
    productImage: ProductImage3,
    productName: 'African Pattern Table Cloth',
    variation: 'Size: Large',
    price: 140,
    inStock: 9,
    status: 'Active',
  },
  {
    productId: 'P12345696',
    productImage: ProductImage4,
    productName: 'African Dance Sculpture',
    variation: 'Material: Bronze',
    price: 350,
    inStock: 4,
    status: 'Inactive',
  },
  {
    productId: 'P12345697',
    productImage: ProductImage5,
    productName: 'Traditional African Stool',
    variation: 'Material: Wood',
    price: 270,
    inStock: 3,
    status: 'Active',
  },
  {
    productId: 'P12345698',
    productImage: ProductImage1,
    productName: 'African Tribal Pattern Blanket',
    variation: 'Color: Multi-colored',
    price: 200,
    inStock: 20,
    status: 'Inactive',
  },
  {
    productId: 'P12345699',
    productImage: ProductImage2,
    productName: 'African Kente Cloth Shawl',
    variation: 'Size: Small',
    price: 65,
    inStock: 13,
    status: 'Active',
  },
  {
    productId: 'P12345700',
    productImage: ProductImage3,
    productName: 'Carved Wooden Elephant Statue',
    variation: 'Size: Large',
    price: 320,
    inStock: 6,
    status: 'Active',
  },
  {
    productId: 'P12345701',
    productImage: ProductImage4,
    productName: 'African Drum Djembe',
    variation: 'Size: Large',
    price: 420,
    inStock: 2,
    status: 'Inactive',
  },
  {
    productId: 'P12345702',
    productImage: ProductImage5,
    productName: 'Handcrafted African Bead Bag',
    variation: 'Size: Medium',
    price: 150,
    inStock: 17,
    status: 'Active',
  },
  {
    productId: 'P12345703',
    productImage: ProductImage1,
    productName: 'African Tribal Painting',
    variation: 'Size: Small',
    price: 185,
    inStock: 8,
    status: 'Active',
  },
  {
    productId: 'P12345704',
    productImage: ProductImage2,
    productName: 'African Animal Figurine Set',
    variation: 'Material: Ceramic',
    price: 220,
    inStock: 12,
    status: 'Inactive',
  },
  {
    productId: 'P12345705',
    productImage: ProductImage3,
    productName: 'Handwoven African Rug',
    variation: 'Size: Large',
    price: 480,
    inStock: 3,
    status: 'Active',
  },
  {
    productId: 'P12345706',
    productImage: ProductImage4,
    productName: 'African Beaded Anklet',
    variation: 'Color: Blue',
    price: 45,
    inStock: 22,
    status: 'Active',
  },
  {
    productId: 'P12345707',
    productImage: ProductImage5,
    productName: 'Traditional African Ceremonial Mask',
    variation: 'Material: Wood',
    price: 350,
    inStock: 5,
    status: 'Inactive',
  },
];
